- name: Deploy to Kubernetes
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ec2-user
    key: ${{ secrets.EC2_KEY }}
    script: |
      export KUBECONFIG=~/.kube/config
      kubectl apply -f /home/ec2-user/k8s/
      kubectl rollout restart deployment backend
      kubectl rollout restart deployment frontend
